[project]
build = "go"

[[tests]]
name = "TestCrawlDelay"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 50

[[tests]]
name = "TestDisallow"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 50
