[project]
build = "go"

[[tests]]
name = "TestExtract"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestCleanHref"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestDownload"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestCrawl"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 10

[[tests]]
name = "TestSearch"
input = ['go', 'test', '-run', '$name', '-json']
expected = "pass"
rubric = 60
